//! Build script: generate the LIB's migration list by scanning
//! `migrations/` at compile time (the lib owns the migrations of its own
//! protocol tables — sync_log, meta, snapshots, pending_ops, tombstones;
//! #31). This list is NOT the consumer's business: `Pglite::init` and
//! `oxylite::server::migrator` merge it with the app's
//! `migrations!("migrations")` list automatically (migration_list.rs) —
//! the demo's `shared` build.rs now generates the APP's list only.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&manifest).join("migrations");
    // Recursive: a file added, removed, renamed or edited inside the
    // directory reruns the script (an edited migration must re-embed).
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<(String, PathBuf)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("migrations: cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension().is_some_and(|x| x == "sql")
                && !p
                    .file_name()
                    .is_some_and(|n| n.to_string_lossy().ends_with(".down.sql"))
        })
        .map(|p| {
            let stem = p
                .file_stem()
                .unwrap_or_else(|| panic!("migrations: {}", p.display()))
                .to_string_lossy()
                .into_owned();
            (stem, p)
        })
        .collect();

    // The convention IS the contract with `sqlx::migrate!` (same
    // directory, `server::migrate`) and with the app's merged client
    // list: `NNNN_name.sql`, zero-padded, so lexicographic order ==
    // applied order on BOTH sides, and the numbers stay globally unique
    // against the app's own migrations. Five digits are rejected on
    // purpose — they would sort before four ("10000" < "9999").
    files.sort();
    for (stem, _) in &files {
        let digits = stem.chars().take_while(|c| c.is_ascii_digit()).count();
        let rest = &stem[digits..];
        if digits != 4 || !rest.starts_with('_') || rest.len() < 2 {
            panic!(
                "migrations: {} does not follow the NNNN_name.sql convention \
                 (four zero-padded digits + underscore) — sqlx::migrate! and the \
                 client's apply-once tracker must agree on order and identity",
                stem
            );
        }
    }

    let mut code = String::from(
        "/// The LIB's schema migrations (its own protocol tables), applied\n\
         /// in order. GENERATED by build.rs — scan of `migrations/`, sorted\n\
         /// lexicographically (= applied order); adding a migration file is\n\
         /// the whole job. Not the consumer's business: the boot/migrator\n\
         /// entry points merge this with the app's `migrations!` list.\n",
    );
    code.push_str("pub static MIGRATIONS: &[(&str, &str)] = &[\n");
    for (stem, path) in &files {
        // include_str! with the absolute path: the generated file lives in
        // OUT_DIR, so relative resolution would miss.
        code.push_str(&format!(
            "    (\"{stem}\", include_str!(\"{}\")),\n",
            path.display()
        ));
    }
    code.push_str("];\n");

    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("migrations.rs");
    fs::write(&out, code).unwrap_or_else(|e| panic!("migrations: write {out:?}: {e}"));
}
