//! Build script: generate the client-side migration list by scanning
//! `migrations/` at compile time, so a new migration file needs no
//! hand-edit of `lib.rs` (a forgotten entry would make the server apply
//! a migration the client never runs — a silent drift bug).
//!
//! The generated `MIGRATIONS` keeps the `&[(&str, &str)]` shape (name
//! stem, embedded SQL) that the PGlite boot snippet applies apply-once,
//! tracked in the client's `meta` table.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&manifest).join("migrations");
    // Recursive: a file added, removed, renamed or edited inside the
    // directory reruns the script (an edited migration must re-embed).
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<(String, PathBuf)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("migrations: cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension().is_some_and(|x| x == "sql")
                && !p
                    .file_name()
                    .is_some_and(|n| n.to_string_lossy().ends_with(".down.sql"))
        })
        .map(|p| {
            let stem = p
                .file_stem()
                .unwrap_or_else(|| panic!("migrations: {}", p.display()))
                .to_string_lossy()
                .into_owned();
            (stem, p)
        })
        .collect();

    // The convention IS the contract with the server's `sqlx::migrate!`
    // (same directory): `NNNN_name.sql`, zero-padded, so lexicographic
    // order == applied order on BOTH sides. Anything else must fail the
    // build here, not drift at runtime — five digits would sort before
    // four ("10000" < "9999"), so the width is enforced on purpose.
    files.sort();
    for (stem, _) in &files {
        let digits = stem.chars().take_while(|c| c.is_ascii_digit()).count();
        let rest = &stem[digits..];
        if digits != 4 || !rest.starts_with('_') || rest.len() < 2 {
            panic!(
                "migrations: {} does not follow the NNNN_name.sql convention \
                 (four zero-padded digits + underscore) — sqlx::migrate! and the \
                 client's apply-once tracker must agree on order and identity",
                stem
            );
        }
    }

    let mut code = String::from(
        "/// The schema migrations, applied in order by both sides from this\n\
         /// single source: the server via `sqlx::migrate!` (same directory,\n\
         /// embedded at compile time, tracked in `_sqlx_migrations`); each\n\
         /// client applies them on first boot against its own PGlite\n\
         /// (tracked in the `meta` table). GENERATED by build.rs — scan of\n\
         /// `migrations/`, sorted lexicographically (= applied order);\n\
         /// adding a migration file is the whole job.\n",
    );
    code.push_str("pub static MIGRATIONS: &[(&str, &str)] = &[\n");
    for (stem, path) in &files {
        // include_str! with the absolute path: the generated file lives in
        // OUT_DIR, so relative resolution would miss.
        code.push_str(&format!(
            "    (\"{stem}\", include_str!(\"{}\")),\n",
            path.display()
        ));
    }
    code.push_str("];\n");

    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("migrations.rs");
    fs::write(&out, code).unwrap_or_else(|e| panic!("migrations: write {out:?}: {e}"));
}
